# Site settings
title: BrainOverfl0w
baseurl: "/blog"
url: "https://www.fredericjacobs.com"

# Build settings
markdown: kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: pretty
destination: fredericjacobs.github.io/blog
